// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Json$ReactTemplate = require("./Json.bs.js");

function Make() {
  var emit = function (socket, obj) {
    socket.emit("message", Json$ReactTemplate.toValidJson(obj));
    return /* () */0;
  };
  var on = function (socket, func) {
    socket.on("message", (function (obj) {
            return Curry._1(func, Json$ReactTemplate.fromValidJson(obj));
          }));
    return /* () */0;
  };
  return [
          (function () {
              return new io();
            }),
          (function (prim) {
              return new io(prim);
            }),
          emit,
          on
        ];
}

exports.Make = Make;
/* No side effect */
