// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Json$ReactTemplate = require("./Json.bs.js");

function Make() {
  var emit = function (server, obj) {
    server.emit("message", Json$ReactTemplate.toValidJson(obj));
    return /* () */0;
  };
  var volatileEmit = function (server, obj) {
    server.volatile.emit("message", Json$ReactTemplate.toValidJson(obj));
    return /* () */0;
  };
  var localEmit = function (server, obj) {
    server.local.emit("message", Json$ReactTemplate.toValidJson(obj));
    return /* () */0;
  };
  return [
          (function (prim) {
              return prim.name;
            }),
          (function (prim) {
              return prim.adapter;
            }),
          (function (prim) {
              return prim.connected;
            }),
          (function (prim, prim$1) {
              prim.clients(prim$1);
              return /* () */0;
            }),
          (function (prim, prim$1) {
              prim.use(prim$1);
              return /* () */0;
            }),
          (function (prim) {
              return prim.sockets();
            }),
          (function (prim, prim$1) {
              return prim.of(prim$1);
            }),
          (function (prim, prim$1) {
              return prim.to(prim$1);
            }),
          emit,
          (function (prim) {
              return prim.volatile;
            }),
          volatileEmit,
          (function (prim) {
              return prim.local;
            }),
          localEmit
        ];
}

exports.Make = Make;
/* No side effect */
